### ISSUE TITLE
onnx export inputs setting

### ISSUE THREAD

**Issue by rGitcy** [LowinLi/fastgpt#1]
您好，请问转出GPT-2 onnx时为什么选这三个输入？我看其他转onnx的版本有的直接使用input ids. 希望得到您的解答，感谢！

**Comment by LowinLi** [comment]
GPT模型在做文本生成的时候，是一个一个token生成出来的，每个token都要跑一次前向传播。因为GPT是单向模型，通过掩码是让前面的token看不到后面的token的。所以后面的token在前向传播时，是不会影响到前面的token。那么前面的token位置的每一层隐藏层的值，在每一次传播时隐藏层的值都是相同的，所以没必要重复计算，所以GPT模型推断时是可以设置cache，cache是从past_key_values传入的。
 
具体可以看看GPT模型的详细理论，看看transformers库推断GPT模型时，开启cache的代码。
 
至于您说的看到其他转onnx的版本，不一定是GPT模型，不需要cache吧。即使是GPT模型，只传入input_ids肯定没办法做cache的

**Comment by rGitcy** [comment]
好的谢谢
