### ISSUE TITLE
Thank you very much for your contribution.

### ISSUE THREAD

**Issue by mocuishle-gdy** [LowinLi/fastgpt#2]
I was confused how to translate transformers' model (included "past_key_value") into onnx model recently,thank u very much!

**Comment by LowinLi** [comment]
The onnx model inputs include "past_key_value" which is [defined by model_wrapper](https://github.com/LowinLi/fastgpt/blob/main/fastgpt/model_wrapper.py#L23).

When GPT generate text, every token is generated by one inference in onnx model.
